CREATE FUNCTION `GIORNO_DELLA_SETTIMANA` (_data DATE)
RETURNS VARCHAR(15)
DETERMINISTIC
READS SQL DATA
BEGIN
	RETURN (SELECT `nome`
			FROM `Giorni`
            WHERE `numero` = (MOD(MOD(DAYOFWEEK(_data) - 2, 7) + 7, 7) + 1));
END
