name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_client_x64_Debug:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Add cl to PATH
      uses: ilammy/msvc-dev-cmd@v1.10.0

    - name: Configure CMake
      working-directory: ${{github.workspace}}/client
      run: cmake --preset x64-windows-debug

    - name: Build
      working-directory: ${{github.workspace}}/client
      run: cmake --build --preset x64-windows-debug

    - name: Test
      working-directory: ${{github.workspace}}/client
      run: ctest --preset x64-windows-debug

  build_client_x64_Release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Add cl to PATH
      uses: ilammy/msvc-dev-cmd@v1.10.0

    - name: Configure CMake
      working-directory: ${{github.workspace}}/client
      run: cmake --preset x64-windows-release

    - name: Build
      working-directory: ${{github.workspace}}/client
      run: cmake --build --preset x64-windows-release

    - name: Test
      working-directory: ${{github.workspace}}/client
      run: ctest --preset x64-windows-release

  build_server_plugin_x64_Debug:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Add cl to PATH
      uses: ilammy/msvc-dev-cmd@v1.10.0

    - name: Configure CMake
      working-directory: ${{github.workspace}}/server/payment-service-plugin
      run: cmake --preset x64-windows-debug

    - name: Build
      working-directory: ${{github.workspace}}/server/payment-service-plugin
      run: cmake --build --preset x64-windows-debug

    - name: Test
      working-directory: ${{github.workspace}}/server/payment-service-plugin
      run: ctest --preset x64-windows-debug
  
  build_server_plugin_x64_Release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Add cl to PATH
      uses: ilammy/msvc-dev-cmd@v1.10.0

    - name: Configure CMake
      working-directory: ${{github.workspace}}/server/payment-service-plugin
      run: cmake --preset x64-windows-release

    - name: Build
      working-directory: ${{github.workspace}}/server/payment-service-plugin
      run: cmake --build --preset x64-windows-release

    - name: Test
      working-directory: ${{github.workspace}}/server/payment-service-plugin
      run: ctest --preset x64-windows-release
